// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppzmsxtufnrukzfsshsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwem1zeHR1Zm5ydWt6ZnNzaHN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNjQ4OTMsImV4cCI6MjA2Mzg0MDg5M30.uMnaq9sUSU3H9cU8_TTI1BixhtVSbztKTgewv7Tlq3M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);